### ISSUE TITLE
근데 루나 제국 코드는 왜 NLR임?

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#100]
약자만 보면 New Lunar Republic이어서 공화정vs군주정 구도일 줄 알았는데 보니까 군주정vs군주정이네? 중간에 설정을 한 번 갈아엎기라도 했나

**Comment by DaePokPung** [comment]
그리포니아 패치 전에도 원래이랬음 그냥 2차창작에서 제일 유명한 국가명이라서 갖다쓴듯
