### ISSUE TITLE
문체에 관한 질문

### ISSUE THREAD

**Issue by AdHoc2675** [DaePokPung/EquestriaAtWar-Korean-Translation#12]
번역에 참여중이긴 하지만, 제가 이 게임을 해보진 않아 글을 어떻게 번역해야할지 감이 잘 안잡히네요. 지금은 그냥 문어체로 번역하고 있는데, 존댓말/반말로 번역해야할 경우는 어떤 것이 있나요?

**Comment by DaePokPung** [comment]
대화문처럼 극히 일부 예외를 제외하고, 게임내 모든 문장은 플레이어에게 설명해주는 입장이기 때문에 가급적이면 모든 문장을 ~합니다, ~습니다 같은 경어체로 끝내주시면 되겠습니다.

**Comment by DaePokPung** [comment]
_desc가 붙은 곳이 설명문이니까 이 부분을 경어체로 쓴다고 생각하시면 되겠습니다
EQS_transequestrian_raillines:0 "범이퀘스트리아 철도" <-제목
EQS_transequestrian_raillines_desc:0 "우리의 새로운 산업적 역량과 앞으로 직면할 갈등을 감안하면, 이퀘스트리아 전역에 철도를 건설하는 프로젝트는 우리에게 있어 매우 유익할 것임이 자명합니다. 셀레스티아 공주님 역시 철도의 발명 이래로 이퀘스트리아 전역을 철도로 연결할 것임을 선언하셨습니다." <-설명문

**Comment by AdHoc2675** [comment]
답변 감사합니다
