### ISSUE TITLE
bat pony의 번역에 대해

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#134]
이때까지 박쥐 포니라고 번역했었음. 그런데 세 포니들이 각각 어스 포니, 페가수스, 유니콘으로 전부 음역되어 있잖아? 그러면 bat pony도 배트 포니로 그대로 음역하는게 어울리지 않을까?

**Comment by DaePokPung** [comment]
배트포니는 쫌금... 빠따포니처럼 들리는데 ㅎㅎ;;
공식번역 상으로는 뱃포니란 단어는 없는걸로 알지만 Flutterbat을 플러터샤이-박쥐로 쓴걸로 보아 박쥐로 쓰는게 의미상의 혼란이 없을거같음 그리고 테스트라라는 음역 표현도 있고
