### ISSUE TITLE
번역 도움

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#147]
Mechanised infantry is distinguished from motorised infantry in that its vehicles provide a degree of protection from hostile fire, as opposed to "soft-skinned" wheeled vehicles (trucks or jeeps) for motorised infantry. Most APCs and IFVs are fully tracked or are all-wheel drive vehicles (6×6 or 8×8), for mobility across rough ground.

체인질링 기계화 보병 중점 설명문구임

**Comment by hyungdugy** [comment]
기계화보병은 차량화 보병을 위한 경장갑 차량(트럭 혹은 지프)과 달리 그들의 차량이 적의 화력으로부터 어느 정도 보호를 제공한다는 점에서 차량화 보병과 구별됩니다. 대부분의 병력수송장갑차(APC)와 전투장갑차(IFV)는 비포장 도로에서 기동성을 위해서 무한궤도이거나 전륜구동 차량(6x6 혹은 8x8)입니다.

ㅋㅋ 밀덕새끼 하나랑 차덕새끼 하나한테 물어서 단어 알아냄 얘들이 이럴때 쓸모가 있네
