### ISSUE TITLE
Update eaw_events_l_english.yml 이거 본 적이 없는 파일인데

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#151]
최근에 추가됨? 내용도 꽤 중요해보여서 이것도 번역해야 할거같은데

**Comment by DaePokPung** [comment]
원래있었음
아주 초창기에 이퀘나라 이벤트들 따로 모아둔건데 지금은 안 쓰이는것들 좀 있어서 확인을 좀 해야함
일단 그것도 번역대상은 맞음
