### ISSUE TITLE
Junior Personal Union Partner 는 뭐라고 번역해야 할까

### ISSUE THREAD

**Issue by keg0150** [DaePokPung/EquestriaAtWar-Korean-Translation#158]
어감을 완전히 살리기는 힘들 것 같고

연합 협력국 정도로 번역해야할까?

괴뢰국이나 종속국 설명할때 나오는건데..

**Comment by UdongNick** [comment]
주니어 파트너: 한 회사, 기관, 연합 등에서 더 적은 권리를 가지고 있는 쪽
퍼스널 유니언: 국경, 법, 정부가 뚜렷히 구분되는 두 개 이상의 국가가  하나의 지도자를 모시는 것

결국 Junior Personal Union Partner는 최고 수준의 자치권이 보장되며 대국적인 문제에 한해서는 의사 결정에도 참여할 수 있지만, 그 영향력이 본국보다 떨어지는 상태의 종속국을 뜻하는거같음.

열세 동반국 정도 생각해봤는데 이것도 별로고, 솔직히 뉘앙스를 살리기는 너무 힘들거같음

**Comment by UdongNick** [comment]
어차피 자기 나라가 열세인지 우세인지는 플레이어가 제일 잘 알테니까 주니어 파트너의 의미는 생략하고 퍼스널 유니언만 번역해서 동군 연합국으로 번역하는게 제일 낫지 않을까

**Comment by DaePokPung** [comment]
윾겜처럼 "동군연합 종속국"으로 번역하면 무난할듯함.

**Comment by keg0150** [comment]
ㅇㅋㅇㅋ 고맙다
