### ISSUE TITLE
이거 오류 수정한게 맞음?

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#164]
![wd](https://user-images.githubusercontent.com/57763783/75115488-580a9280-56a2-11ea-95a7-a5245529b606.PNG)

우리의 약속지키기 밑에 desc가 오는게 맞는거 아님?

**Comment by DaePokPung** [comment]
그런거 같은데
난 얼핏보고 _desc빠진거 붙인줄 알았더니 반대였누
