### ISSUE TITLE
슬슬 창작모드에 한번 올려보는것도 낫지 않음?

### ISSUE THREAD

**Issue by keg0150** [DaePokPung/EquestriaAtWar-Korean-Translation#168]
몇몇국가는 다됐고 나머지도 얼추 된곳 꽤 있는데...

슬슬 올려봐도 괜찮지 않을까

**Comment by DaePokPung** [comment]
사람들 의견을 좀 더 들어보고 싶었는데 딱히 반응이 없네
내부 테스트용 하나 있어도 상관은 없을것 같으니 좀있다가 미등록으로 하나 올리겠음

**Comment by DaePokPung** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1912668247

**Comment by keg0150** [comment]
오...나도 내일 피방가서 한번 돌려보겠음 그럼
