### ISSUE TITLE
디코 하나 파면 안되냐?

### ISSUE THREAD

**Issue by gyhs** [DaePokPung/EquestriaAtWar-Korean-Translation#184]
나 번역팀에 있는데 디코에서 문제 하나도 없다 ㄹㅇ

**Comment by gyhs** [comment]
물어볼 사람이 ㅈㄴ 부족하니까 힘듬

**Comment by DaePokPung** [comment]
디코를 써본적이 거의 없어서 어떻게 해야할지 잘 모르겠네...
아직은 여기서 토론하고 모르겠으면 적당히 번역해 놓으면 나중에 인게임 검수 등을 통해서 다시 수정하는 중이라 딱히 디코 필요성을 못느끼는 중인데

**Comment by gyhs** [comment]
근데 ㅈ대로 써놓으면 그것도 그거대로 짜증나지 않냐
뭐 일단은 그것밖에 없는거네 단어장 참고해가면서 해야지 뭐

**Comment by DaePokPung** [comment]
솔직히 이게 실존 나라, 인명이 아니다보니 이건 어떻게 쓰냐 이런거 물어보는게 좀 무의미한거 같음
문제 제기하는 사람이 아예 없는건 아닌데 그정도야 여기서 해결해도 되는 문제고
단어 통일 문제도 인원수가 적고 대량 번역작업이 없다보니 나중에 맞추기도 쉽고
일단 인원수 더 많아져서 이런 방식이 난잡해진다 싶으면 다시 고려해보겠음

**Comment by gyhs** [comment]
ㅇㅋ
