### ISSUE TITLE
아코네이트를 뭐라고 번역해야 할까?

### ISSUE THREAD

**Issue by SamMinGrifforn** [DaePokPung/EquestriaAtWar-Korean-Translation#188]
집정관국?

**Comment by DaePokPung** [comment]
https://github.com/DaePokPung/EquestriaAtWar-Korean-Translation/pull/115
난 문맥상 집정관, 집정관직, 집정관 영지 등으로 로 했음. 자치령을 뜻한다면 ~국 해도 될듯?
