### ISSUE TITLE
여기 컨텐츠 다 즐기려면 어떤 dlc 필요함?

### ISSUE THREAD

**Issue by hyungdugy** [DaePokPung/EquestriaAtWar-Korean-Translation#191]
세일해서 본편 샀는데 필요한 dlc 있음? 반복돌인가 뭔가는 잘 모르겟다

**Comment by UdongNick** [comment]
EaW 공식 위키에 따르면

Together For Victory : 게임 내에서 속국 메커니즘을 적극 활용하는 국가는 이퀘스트리아 뿐이지만, 그 외의 국가로도 속국을 굴릴 수 있는 전문가들에게 추천.
Death or Dishonour : 구식장비 일괄 교체 기능이 추가됨. 딱히 쓰이는 부분 없음.
Waking the Tiger : 장군/원수 특성, 전장 기상상태, 국경분쟁 기능이 추가됨. 쓰이는 부분 엄청 많음.
Man the Guns : 망명정부 추가됨. 딱히 쓰이는 부분 없음.
La Resistance : 첩보, 사보타주 추가됨. 최신 DLC라 현 버전에서는 안 쓰일거임.

DLC가 있으면 좋고, 없어도 괜찮대

**Comment by UdongNick** [comment]
일단 살거면 쓰이는 부분 많은 Waking the Tiger부터 사는거 추천

**Comment by hyungdugy** [comment]
ㄳㄳ 스텔라리스는 많이 해봤는데 호이는 안해봐서 잘 몰랐음
