### ISSUE TITLE
지도자 이름 번역하는법

### ISSUE THREAD

**Issue by gyhs** [DaePokPung/EquestriaAtWar-Korean-Translation#201]
일단 카라로 예시를 들어보겠음
준비물로는 history>countries 폴더속의 파일들이 필요함

**Comment by gyhs** [comment]
capital = 64

oob = "GER"
set_naval_oob= "GER_naval"

add_ideas = {
	GER_victors_of_wwi
	GER_quenched_militarism
	ZO_idea
	GER_imperial_pride

	limited_conscription

	GER_Franz_von_Papen_hog_ade
	GER_Friedrich_Werner_von_der_Schulenberg_for_ade
	GER_Hjalmar_Schacht_eco_ade
	GER_Johann_von_Bernstorff_sec_ade

	GER_August_Von_Mackensen_carm_pau
	GER_Manfred_Freiherr_von_Richthofen_cair_ade
	GER_Hans_von_Seeckt_cos_pau
}

### Starting Technologies ###

set_technology = {
	### General ###
	electronic_mechanical_engineering = 1
	fuel_silos = 1

	### Tanks ###
	gwtank = 1
	basic_light_tank = 1
	basic_heavy_tank = 1

	### Infantry ###
	infantry_weapons = 1
	infantry_weapons1 = 1
	tech_support = 1
	motorised_infantry = 1
	tech_recon = 1
	tech_engineers = 1
	tech_mountaineers = 1
	marines = 1
	gw_artillery = 1
	interwar_antiair = 1

	### Air ###
	early_fighter = 1
	naval_bomber1 = 1
	early_bomber = 1
	cv_early_fighter = 1
	cv_CAS1 = 1
	cv_naval_bomber1 = 1
	fighter1 = 1
	tactical_bomber1 = 1
	strategic_bomber1 = 1
	CAS1 = 1
}

### Navy - MtG ###

if = {
	limit = {
		has_dlc = "Man the Guns"
	}
	set_technology = {
		weltkrieg_light_ship_hull = 1
		contact_mine = 1
		light_ship_hull_1936 = 1
		weltkrieg_cruiser_hull = 1
		cruiser_hull_1936 = 1
		weltkrieg_submarine_hull = 1
		submarine_hull_1936 = 1
		cruiser_submarine = 1
		carrier_conversion = 1
		carrier_hull_1936 = 1
		ship_hull_revived_ac = 1
		weltkrieg_heavy_ship_hull = 1
		heavy_ship_hull_1936 = 1
		ship_hull_super_heavy = 1

		## Modules##
		early_torpedo = 1
		weltkrieg_naval_gunnery = 1
		naval_ammo_one = 1
		light_battery_one = 1
		improved_ship_torpedo_launcher = 1
		basic_cruiser_armor_scheme = 1
		weltkrieg_naval_gunnery = 1
		naval_ammo_one = 1
		basic_heavy_armor_scheme = 1
		capital_gunnery_one = 1
		weltkrieg_naval_gunnery = 1
		naval_ammo_one = 1
		naval_ammo_two = 1

		### Transport ###
		transport = 1
	}
}

### Navy - Non MtG ###

if = {
	limit = {
		NOT = {
			has_dlc = "Man the Guns"
		}
	}
	set_technology = {
		weltkrieg_destroyer_nonmtg = 1
		interwar_destroyer_nonmtg = 1
		weltkrieg_cruiser_nonmtg = 1
		interwar_cruiser_nonmtg = 1
		weltkrieg_submarine_nonmtg = 1
		interwar_submarine_nonmtg = 1
		weltkrieg_armored_cruiser_nonmtg = 1
		interwar_armored_cruiser_nonmtg = 1
		weltkrieg_fast_battleship_nonmtg = 1
		interwar_fast_battleship_nonmtg = 1
		weltkrieg_dreadnought_nonmtg = 1
		super_heavy_dreadnought_nonmtg = 1
		weltkrieg_carrier_nonmtg = 1
		interwar_carrier_nonmtg = 1 

		### Transport ###
		transport_n = 1
	}
}

POL = { give_military_access = GER }
DKB = { give_military_access = GER }
GEO = { give_military_access = GER }
AZE = { give_military_access = GER }
OTT = { give_military_access = GER }
LEC = { give_military_access = GER }

give_guarantee = DKB
give_guarantee = GEO
give_guarantee = AZE
give_guarantee = LEC

AZE = {
	give_resource_rights = {
		state = 990
		receiver = GER
	}
}

set_research_slots = 4
set_convoys = 400
set_stability = 0.6

set_global_flag = GER_has_oil
set_country_flag = legation_council_vote

diplomatic_relation = { country = AUS relation = non_aggression_pact }

add_opinion_modifier = { target = ENG modifier = embargo }
add_opinion_modifier = { target = BHC modifier = embargo }
add_opinion_modifier = { target = FRA modifier = embargo }
add_opinion_modifier = { target = CSA modifier = embargo }
add_opinion_modifier = { target = DEH modifier = embargo }
add_opinion_modifier = { target = FNG modifier = embargo }
add_opinion_modifier = { target = SRI modifier = embargo }
add_opinion_modifier = { target = GEO modifier = embargo }
add_opinion_modifier = { target = SOV modifier = embargo }
add_opinion_modifier = { target = SQI modifier = embargo }
add_opinion_modifier = { target = CNT modifier = embargo }
add_opinion_modifier = { target = LEC modifier = LEC_member }
add_opinion_modifier = { target = MAF modifier = colonial_master }
add_opinion_modifier = { target = GEA modifier = colonial_master }
add_opinion_modifier = { target = HAI modifier = HAI_foreign_council }

set_politics = {
	ruling_party = authoritarian_democrat
	last_election = "1932.3.8"
	election_frequency = 60
	elections_allowed = yes
}

set_popularities = {
	totalist = 1
	radical_socialist = 3
	syndicalist = 2
	social_democrat = 22
	social_liberal = 6
	market_liberal = 3
	social_conservative = 12
	authoritarian_democrat = 42
	paternal_autocrat = 7
	national_populist = 2
}

set_autonomy = {
	target = LIT
	autonomy_state = kr_default_puppet
}
set_autonomy = {
	target = WHR
	autonomy_state = kr_default_puppet
}
set_autonomy = {
	target = MAF
	autonomy_state = kr_colonial_government
}
set_autonomy = {
	target = GEA
	autonomy_state = kr_colonial_government
}
set_autonomy = {
	target = MOR
	autonomy_state = kr_autonomous_puppet
}

if = {
	limit = {
		has_dlc = "Together for Victory"
	}
	add_to_tech_sharing_group = german_research
	every_country = {
		limit = {
			is_subject_of = GER
		}
		add_to_tech_sharing_group = german_research
	}
}

create_faction = Mittelmacht

add_to_faction = GER
add_to_faction = BEL
add_to_faction = LIT
add_to_faction = BAT
add_to_faction = WHR
add_to_faction = UKR
add_to_faction = MOR
add_to_faction = MAF
add_to_faction = GEA

news_event = { id = gerfla.1 days = 238 }

country_event = {
	id = black.1
	days = 34
}

country_event = {
	id = mittel.43
	days = 90
}

country_event = { #Tintin and the Blue Lotus
	id = literature.15
	days = 952
}

### Trade ###
create_import = {
	resource = oil
	factories = 3
	exporter = ROM
}
create_import = {
	resource = oil
	factories = 1
	exporter = AZE
}

create_country_leader = {
	name = "Rudolf Hess"
	desc = "POLITICS_RUDOLF_HESS_DESC"
	picture = "Portrait_Germany_Rudolf_Hess.tga"
	expire = "1965.1.1"
	ideology = national_populist_subtype
}

create_country_leader = {
	name = "Wilhelm Pieck"
	desc = "POLITICS_WILHELM_PIECK_DESC"
	picture = "Portrait_Germany_Wilhelm_Pieck_I.tga"
	expire = "1965.1.1"
	ideology = totalist_subtype
}

create_country_leader = {
	name = "Ernst Thälmann"
	desc = "POLITICS_ERNST_THALMANN_DESC"
	picture = "Portrait_Germany_Ernst_Thalmann.tga"
	expire = "1965.1.1"
	ideology = syndicalist_subtype
}

create_country_leader = {
	name = "Rudolf Rocker"
	desc = "POLITICS_RUDOLF_ROCKER_DESC"
	picture = "Portrait_Germany_Rudolf_Rocker_I.tga"
	expire = "1965.1.1"
	ideology = radical_socialist_subtype
}

create_country_leader = {
	name = "Erich Koch-Weser"
	desc = "POLITICS_ERICH_KOCH_WESER_DESC"
	picture = "Portrait_Germany_Erich_Koch_Weser.tga"
	expire = "1965.1.1"
	ideology = social_liberal_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = social_conservative_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = market_liberal_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = social_democrat_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = paternal_autocrat_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = authoritarian_democrat_subtype
}

create_field_marshal = {
	name = "Gerd von Rundstedt"
	picture = "Portrait_Germany_Gerd_von_Rundstedt_kr.tga"
	traits = { defensive_doctrine offensive_doctrine }
	skill = 4
	attack_skill = 2
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 4
}

create_field_marshal = {
	name = "Rupprecht von Bayern"
	picture = "Portrait_Germany_Rupprecht_Bayern_kr.tga"
	traits = { trait_cautious inflexible_strategist defensive_doctrine organizer thorough_planner }
	skill = 4
	attack_skill = 2
	defense_skill = 4
	planning_skill = 4
	logistics_skill = 3
}

create_field_marshal = {
	name = "August von Mackensen"
	picture = "Portrait_Germany_August_Mackensen_kr.tga"
	traits = { offensive_doctrine old_guard }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 3
	id = 983
}

create_field_marshal = {
	name = "Wilhelm von Preußen"
	picture = "Portrait_Germany_Wilhelm_III_field_marshall.tga"
	traits = { old_guard }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 4
	logistics_skill = 2
}

create_corps_commander = {
	name = "Erich von Manstein"
	picture = "Portrait_Germany_Erich_von_Manstein_kr.tga"
	traits = { trickster armor_officer brilliant_strategist trait_engineer }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 3
	logistics_skill = 4
}

create_corps_commander = {
	name = "Heinz Guderian"
	picture = "Portrait_Germany_Heinz_Guderian_kr.tga"
	traits = { trickster brilliant_strategist panzer_leader armor_officer career_officer }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 3
}

create_corps_commander = {
	name = "Walter Model"
	picture = "Portrait_Germany_Walter_Model_kr.tga"
	traits = { politically_connected trait_cautious harsh_leader brilliant_strategist trickster }
	skill = 4
	attack_skill = 3
	defense_skill = 5
	planning_skill = 2
	logistics_skill = 3
}

create_corps_commander = {
	name = "Werner von Blomberg"
	picture = "Portrait_Germany_Werner_von_Blomberg.tga"
	traits = { trickster armor_officer career_officer }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 2
}

create_corps_commander = {
	name = "Günther von Kluge"
	picture = "Portrait_Germany_Gunther_Kluge_kr.tga"
	traits = { career_officer armor_officer }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 3
}

create_corps_commander = {
	name = "Erwin von Witzleben"
	picture = "Portrait_Germany_Erwin_von_Witzleben_kr.tga"
	traits = { skilled_staffer career_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 3
	planning_skill = 2
	logistics_skill = 3
}

create_corps_commander = {
	name = "Wilhelm Ritter von Leeb"
	picture = "Portrait_Germany_Wilhelm_Ritter_von_Leeb_kr.tga"
	traits = { skilled_staffer infantry_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 3
	planning_skill = 3
	logistics_skill = 2
}

create_corps_commander = {
	name = "Albert Kesselring"
	picture = "Portrait_Germany_Albert_Kesselring_kr.tga"
	traits = { inflexible_strategist infantry_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 3
}

create_corps_commander = {
	name = "Eberhard von Mackensen"
	picture = "Portrait_Germany_Eberhard_Mackensen_kr.tga"
	traits = { cavalry_leader cavalry_officer }
	skill = 3
	attack_skill = 4
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Eduard Dietl"
	picture = "Portrait_Germany_Eduard_Dietl_kr.tga"
	traits = { winter_specialist commando }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 4
}

create_corps_commander = {
	name = "Erich Hoepner"
	picture = "Portrait_Germany_Erich_Hoepner_kr.tga"
	traits = { armor_officer trait_reckless }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 3
}

create_corps_commander = {
	name = "Ewald von Kleist"
	picture = "Portrait_Germany_Ewald_Kleist_kr.tga"
	traits = { skilled_staffer }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 2
}

create_corps_commander = {
	name = "Fedor von Bock"
	picture = "Portrait_Germany_Fedor_Bock_kr.tga"
	traits = { brilliant_strategist harsh_leader trait_cautious }
	skill = 3
	attack_skill = 4
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Friedrich Paulus"
	picture = "Portrait_Germany_Friedrich_Paulus_kr.tga"
	traits = { infantry_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 3
}

create_corps_commander = {
	name = "Georg von Küchler"
	picture = "Portrait_Germany_Georg_Kuchler_kr.tga"
	traits = { politically_connected career_officer }
	skill = 3
	attack_skill = 3
	defense_skill = 3
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Franz Halder"
	picture = "Portrait_Germany_Franz_Halder_kr.tga"
	traits = { organizer }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 4
	logistics_skill = 2
}

create_corps_commander = {
	name = "Gotthard Heinrici"
	picture = "Portrait_Germany_Gotthard_Heinrici_kr.tga"
	traits = { trait_engineer fortress_buster }
	skill = 3
	attack_skill = 4
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Hermann Hoth"
	picture = "Portrait_Germany_Hermann_Hoth_kr.tga"
	traits = { infantry_officer infantry_expert }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 4
	logistics_skill = 2
}

create_corps_commander = {
	name = "Franz von Bayern"
	picture = "Portrait_Germany_Franz_Bayern_kr.tga"
	traits = { trait_engineer fortress_buster hill_fighter }
	skill = 2
	attack_skill = 1
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}



create_navy_leader = {
	name = "Karl Dönitz"
	picture = "Portrait_Germany_Karl_Donitz_kr.tga"
	traits = { seawolf silent_hunter }
	skill = 4
	attack_skill = 4
	defense_skill = 2
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Erich Raeder"
	picture = "Portrait_Germany_Erich_Raeder_kr.tga"
	traits = { ironside }
	skill = 5
	attack_skill = 5
	defense_skill = 3
	maneuvering_skill = 4
	coordination_skill = 4
}

create_navy_leader = {
	name = "Lothar von Arnauld de la Perière"
	picture = "Portrait_Germany_Lothar_Arnauld_Periere_kr.tga"
	traits = { seawolf }
	skill = 4
	attack_skill = 3
	defense_skill = 4
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Alfred Saalwächter"
	picture = "Portrait_Germany_Alfred_Saalwachter_kr.tga"
	traits = { }
	skill = 3
	attack_skill = 3
	defense_skill = 3
	maneuvering_skill = 3
	coordination_skill = 4
}

create_navy_leader = {
	name = "Hermann Boehm"
	picture = "Portrait_Germany_Hermann_Boehm_kr.tga"
	traits = { superior_tactician }
	skill = 4
	attack_skill = 4
	defense_skill = 4
	maneuvering_skill = 3
	coordination_skill = 3
}

create_navy_leader = {
	name = "Wilhelm Marschall"
	picture = "Portrait_Germany_Wilhelm_Marschall_kr.tga"
	traits = { blockade_runner }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	maneuvering_skill = 3
	coordination_skill = 3
}

create_navy_leader = {
	name = "Ludwig von Reuter"
	picture = "Portrait_Germany_Ludwig_Reuter_kr.tga"
	traits = { ironside superior_tactician old_guard_navy }
	skill = 5
	id = 984
	attack_skill = 5
	defense_skill = 4
	maneuvering_skill = 4
	coordination_skill = 5
}

create_navy_leader = {
	name = "Wilhelm Souchon"
	picture = "Portrait_Germany_Wilhelm_Souchon_kr.tga"
	traits = { spotter old_guard_navy }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	maneuvering_skill = 3
	coordination_skill = 3
}

create_navy_leader = {
	name = "Max Valentiner"
	picture = "Portrait_Germany_Max_Valentiner_kr.tga"
	traits = { seawolf }
	skill = 4
	attack_skill = 4
	defense_skill = 1
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Rolf Carls"
	picture = "Portrait_Germany_Rolf_Carls_kr.tga"
	traits = { blockade_runner old_guard_navy }
	skill = 4
	attack_skill = 3
	defense_skill = 4
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Günther Lütjens"
	picture = "Portrait_Germany_Gunther_Lutjens_kr.tga"
	traits = { }
	skill = 3
	attack_skill = 3
	defense_skill = 1
	maneuvering_skill = 2
	coordination_skill = 3
}

create_navy_leader = {
	name = "Otto Ciliax"
	picture = "Portrait_Germany_Otto_Ciliax_kr.tga"
	traits = { blockade_runner }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	maneuvering_skill = 3
	coordination_skill = 2
}

create_navy_leader = {
	name = "Bernhard Rogge"
	picture = "Portrait_Germany_Bernhard_Rogge_kr.tga"
	traits = { seawolf }
	skill = 1
	attack_skill = 2
	defense_skill = 1
	maneuvering_skill = 2
	coordination_skill = 1
}

GER_start_naval_variant = yes

**Comment by gyhs** [comment]
create_country_leader = {
	name = "Rudolf Hess"
	desc = "POLITICS_RUDOLF_HESS_DESC"
	picture = "Portrait_Germany_Rudolf_Hess.tga"
	expire = "1965.1.1"
	ideology = national_populist_subtype
}

create_country_leader = {
	name = "Wilhelm Pieck"
	desc = "POLITICS_WILHELM_PIECK_DESC"
	picture = "Portrait_Germany_Wilhelm_Pieck_I.tga"
	expire = "1965.1.1"
	ideology = totalist_subtype
}

create_country_leader = {
	name = "Ernst Thälmann"
	desc = "POLITICS_ERNST_THALMANN_DESC"
	picture = "Portrait_Germany_Ernst_Thalmann.tga"
	expire = "1965.1.1"
	ideology = syndicalist_subtype
}

create_country_leader = {
	name = "Rudolf Rocker"
	desc = "POLITICS_RUDOLF_ROCKER_DESC"
	picture = "Portrait_Germany_Rudolf_Rocker_I.tga"
	expire = "1965.1.1"
	ideology = radical_socialist_subtype
}

create_country_leader = {
	name = "Erich Koch-Weser"
	desc = "POLITICS_ERICH_KOCH_WESER_DESC"
	picture = "Portrait_Germany_Erich_Koch_Weser.tga"
	expire = "1965.1.1"
	ideology = social_liberal_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = social_conservative_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = market_liberal_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = social_democrat_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = paternal_autocrat_subtype
}

create_country_leader = {
	name = "Wilhelm II"
	desc = "POLITICS_WILHELM_II_DESC"
	picture = "Portrait_Germany_Wilhelm_II.tga"
	expire = "1965.1.1"
	ideology = authoritarian_democrat_subtype
}

create_field_marshal = {
	name = "Gerd von Rundstedt"
	picture = "Portrait_Germany_Gerd_von_Rundstedt_kr.tga"
	traits = { defensive_doctrine offensive_doctrine }
	skill = 4
	attack_skill = 2
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 4
}

create_field_marshal = {
	name = "Rupprecht von Bayern"
	picture = "Portrait_Germany_Rupprecht_Bayern_kr.tga"
	traits = { trait_cautious inflexible_strategist defensive_doctrine organizer thorough_planner }
	skill = 4
	attack_skill = 2
	defense_skill = 4
	planning_skill = 4
	logistics_skill = 3
}

create_field_marshal = {
	name = "August von Mackensen"
	picture = "Portrait_Germany_August_Mackensen_kr.tga"
	traits = { offensive_doctrine old_guard }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 3
	id = 983
}

create_field_marshal = {
	name = "Wilhelm von Preußen"
	picture = "Portrait_Germany_Wilhelm_III_field_marshall.tga"
	traits = { old_guard }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 4
	logistics_skill = 2
}

create_corps_commander = {
	name = "Erich von Manstein"
	picture = "Portrait_Germany_Erich_von_Manstein_kr.tga"
	traits = { trickster armor_officer brilliant_strategist trait_engineer }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 3
	logistics_skill = 4
}

create_corps_commander = {
	name = "Heinz Guderian"
	picture = "Portrait_Germany_Heinz_Guderian_kr.tga"
	traits = { trickster brilliant_strategist panzer_leader armor_officer career_officer }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 3
}

create_corps_commander = {
	name = "Walter Model"
	picture = "Portrait_Germany_Walter_Model_kr.tga"
	traits = { politically_connected trait_cautious harsh_leader brilliant_strategist trickster }
	skill = 4
	attack_skill = 3
	defense_skill = 5
	planning_skill = 2
	logistics_skill = 3
}

create_corps_commander = {
	name = "Werner von Blomberg"
	picture = "Portrait_Germany_Werner_von_Blomberg.tga"
	traits = { trickster armor_officer career_officer }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 2
}

create_corps_commander = {
	name = "Günther von Kluge"
	picture = "Portrait_Germany_Gunther_Kluge_kr.tga"
	traits = { career_officer armor_officer }
	skill = 4
	attack_skill = 3
	defense_skill = 3
	planning_skill = 4
	logistics_skill = 3
}

create_corps_commander = {
	name = "Erwin von Witzleben"
	picture = "Portrait_Germany_Erwin_von_Witzleben_kr.tga"
	traits = { skilled_staffer career_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 3
	planning_skill = 2
	logistics_skill = 3
}

create_corps_commander = {
	name = "Wilhelm Ritter von Leeb"
	picture = "Portrait_Germany_Wilhelm_Ritter_von_Leeb_kr.tga"
	traits = { skilled_staffer infantry_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 3
	planning_skill = 3
	logistics_skill = 2
}

create_corps_commander = {
	name = "Albert Kesselring"
	picture = "Portrait_Germany_Albert_Kesselring_kr.tga"
	traits = { inflexible_strategist infantry_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 3
}

create_corps_commander = {
	name = "Eberhard von Mackensen"
	picture = "Portrait_Germany_Eberhard_Mackensen_kr.tga"
	traits = { cavalry_leader cavalry_officer }
	skill = 3
	attack_skill = 4
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Eduard Dietl"
	picture = "Portrait_Germany_Eduard_Dietl_kr.tga"
	traits = { winter_specialist commando }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 4
}

create_corps_commander = {
	name = "Erich Hoepner"
	picture = "Portrait_Germany_Erich_Hoepner_kr.tga"
	traits = { armor_officer trait_reckless }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 3
}

create_corps_commander = {
	name = "Ewald von Kleist"
	picture = "Portrait_Germany_Ewald_Kleist_kr.tga"
	traits = { skilled_staffer }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 2
}

create_corps_commander = {
	name = "Fedor von Bock"
	picture = "Portrait_Germany_Fedor_Bock_kr.tga"
	traits = { brilliant_strategist harsh_leader trait_cautious }
	skill = 3
	attack_skill = 4
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Friedrich Paulus"
	picture = "Portrait_Germany_Friedrich_Paulus_kr.tga"
	traits = { infantry_officer }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 3
	logistics_skill = 3
}

create_corps_commander = {
	name = "Georg von Küchler"
	picture = "Portrait_Germany_Georg_Kuchler_kr.tga"
	traits = { politically_connected career_officer }
	skill = 3
	attack_skill = 3
	defense_skill = 3
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Franz Halder"
	picture = "Portrait_Germany_Franz_Halder_kr.tga"
	traits = { organizer }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 4
	logistics_skill = 2
}

create_corps_commander = {
	name = "Gotthard Heinrici"
	picture = "Portrait_Germany_Gotthard_Heinrici_kr.tga"
	traits = { trait_engineer fortress_buster }
	skill = 3
	attack_skill = 4
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}

create_corps_commander = {
	name = "Hermann Hoth"
	picture = "Portrait_Germany_Hermann_Hoth_kr.tga"
	traits = { infantry_officer infantry_expert }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	planning_skill = 4
	logistics_skill = 2
}

create_corps_commander = {
	name = "Franz von Bayern"
	picture = "Portrait_Germany_Franz_Bayern_kr.tga"
	traits = { trait_engineer fortress_buster hill_fighter }
	skill = 2
	attack_skill = 1
	defense_skill = 2
	planning_skill = 2
	logistics_skill = 2
}



create_navy_leader = {
	name = "Karl Dönitz"
	picture = "Portrait_Germany_Karl_Donitz_kr.tga"
	traits = { seawolf silent_hunter }
	skill = 4
	attack_skill = 4
	defense_skill = 2
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Erich Raeder"
	picture = "Portrait_Germany_Erich_Raeder_kr.tga"
	traits = { ironside }
	skill = 5
	attack_skill = 5
	defense_skill = 3
	maneuvering_skill = 4
	coordination_skill = 4
}

create_navy_leader = {
	name = "Lothar von Arnauld de la Perière"
	picture = "Portrait_Germany_Lothar_Arnauld_Periere_kr.tga"
	traits = { seawolf }
	skill = 4
	attack_skill = 3
	defense_skill = 4
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Alfred Saalwächter"
	picture = "Portrait_Germany_Alfred_Saalwachter_kr.tga"
	traits = { }
	skill = 3
	attack_skill = 3
	defense_skill = 3
	maneuvering_skill = 3
	coordination_skill = 4
}

create_navy_leader = {
	name = "Hermann Boehm"
	picture = "Portrait_Germany_Hermann_Boehm_kr.tga"
	traits = { superior_tactician }
	skill = 4
	attack_skill = 4
	defense_skill = 4
	maneuvering_skill = 3
	coordination_skill = 3
}

create_navy_leader = {
	name = "Wilhelm Marschall"
	picture = "Portrait_Germany_Wilhelm_Marschall_kr.tga"
	traits = { blockade_runner }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	maneuvering_skill = 3
	coordination_skill = 3
}

create_navy_leader = {
	name = "Ludwig von Reuter"
	picture = "Portrait_Germany_Ludwig_Reuter_kr.tga"
	traits = { ironside superior_tactician old_guard_navy }
	skill = 5
	id = 984
	attack_skill = 5
	defense_skill = 4
	maneuvering_skill = 4
	coordination_skill = 5
}

create_navy_leader = {
	name = "Wilhelm Souchon"
	picture = "Portrait_Germany_Wilhelm_Souchon_kr.tga"
	traits = { spotter old_guard_navy }
	skill = 3
	attack_skill = 3
	defense_skill = 2
	maneuvering_skill = 3
	coordination_skill = 3
}

create_navy_leader = {
	name = "Max Valentiner"
	picture = "Portrait_Germany_Max_Valentiner_kr.tga"
	traits = { seawolf }
	skill = 4
	attack_skill = 4
	defense_skill = 1
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Rolf Carls"
	picture = "Portrait_Germany_Rolf_Carls_kr.tga"
	traits = { blockade_runner old_guard_navy }
	skill = 4
	attack_skill = 3
	defense_skill = 4
	maneuvering_skill = 4
	coordination_skill = 3
}

create_navy_leader = {
	name = "Günther Lütjens"
	picture = "Portrait_Germany_Gunther_Lutjens_kr.tga"
	traits = { }
	skill = 3
	attack_skill = 3
	defense_skill = 1
	maneuvering_skill = 2
	coordination_skill = 3
}

create_navy_leader = {
	name = "Otto Ciliax"
	picture = "Portrait_Germany_Otto_Ciliax_kr.tga"
	traits = { blockade_runner }
	skill = 3
	attack_skill = 2
	defense_skill = 2
	maneuvering_skill = 3
	coordination_skill = 2
}

create_navy_leader = {
	name = "Bernhard Rogge"
	picture = "Portrait_Germany_Bernhard_Rogge_kr.tga"
	traits = { seawolf }
	skill = 1
	attack_skill = 2
	defense_skill = 1
	maneuvering_skill = 2
	coordination_skill = 1
}
이만큼만 뜯어내고 나머지는 지우자

**Comment by gyhs** [comment]
여기서 name = "Wilhelm II"를 name = "빌헬름 2세"로 번역하면 끝임

**Comment by gyhs** [comment]
이렇게 하면 지도자 이름까지 한글화 되어서 읽기 편해질거임

**Comment by DaePokPung** [comment]
정보 ㄳㄳ
근데 이렇게 하니까 중점 조건 중에 "~~은(는) 현재 국가 지도자임" 이 부분이 여전히 영어라서 인식이 안되는데 여기도 따로 한글화하는 방법밖엔 없는거임?

**Comment by gyhs** [comment]
그거는 커스텀 툴팁이라고 어딘가에 적혀있는게 있을거임
예시를 들자면
예시_tt:0 "[Get.Leader]는 현재 국가 지도자임"
이런 식으로 되어있을거임 (아마도)

**Comment by DaePokPung** [comment]
찾아보니까 common 안에 코딩되어 있네
has_country_leader = { ruling_only = yes name = "이름" }
이 부분까지 한글화해야 인식이 되는 거 같은데 업뎃마다 확인하려면 좀 빡시겠다
일단 ㅇㅋ

**Comment by UdongNick** [comment]
그러면 문서마다 지도자 이름 달라서 검수하고 할 필요 없는거임?

**Comment by DaePokPung** [comment]
그냥 국가 메뉴에 지도자 이름이 한글로 바뀌는거임
어찌됐건 검수는 해야함
