### ISSUE TITLE
스크립트 사용법좀 알려줄수 있음? 

### ISSUE THREAD

**Issue by gyhs** [DaePokPung/EquestriaAtWar-Korean-Translation#215]
카라 번역에서 사용하게 ㅇㅇ

**Comment by gyhs** [comment]
그리고 여기 Readme.md에 써져있는거좀 빌려감
미안
잘만들었길래

**Comment by DaePokPung** [comment]
내가 다 만든건 아니긴한데 일단 알겠음 ㅇㅇ스크립트도 다른사람이 만들었긴한데

스크립트 사용법은 wordbook_countries.js 안에 내용 전부 복사하고
크롬으로 https://equestria-at-war.fandom.com/wiki/List_of_Countries 들어가서
F12로 개발자도구 켜고 Console탭 들어가서 복사한 내용 그대로 침
그 다음에 getCountries() 입력하면 코드가 나오는데 그거 그대로 복사해서 깃허브에 붙여넣으면 리드미 파일에 국가코드 양식이 나옴

**Comment by gyhs** [comment]
고마우이
