### ISSUE TITLE
이거 게임 내 출력에는 영향 없는 거임?

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#219]
![gttg](https://user-images.githubusercontent.com/57763783/76154545-80be6d80-6121-11ea-8a42-931cb1e664b5.PNG)

다른 줄들이랑은 다르게 한 칸씩 덜 띄워져 있던데

**Comment by DaePokPung** [comment]
앞에 띄어쓰기는 상관없는거 같음
