### ISSUE TITLE
country_AET_l_english.yml 번역 중에 이해가 안되는 부분이 있어서

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#23]
AET가 그라이프발트 로컬 파일이란 말이지? 그런데

greifwald.1.t:0 "우리의 친구 그라이프발트"
greifwald.1.d:0 "최근 그리펜하임에 외교 사절단을 파견한 그라이프발트의 [AET.GetLeader]는 제국이 그의 소국에게 무역을 개방해 경제적 유대를 증진시킬 것을 제안했다. 그것이 그 지역에서 아퀼레리아의 영향력을 얼마나 억제할 수 있을지를 언급하면서 말이다. 어떻게 해야 할까?"
greifwald.1.a:0 "흠... 아퀼레이아한테 한방 먹일 수 있겠군. 받아들이지."
greifwald.1.b:0 "그건 돈낭비같은데?"

를 보면 말하는 주체가 그라이프발트가 아니라 그리포니아처럼 보인단말야? 내가 이해를 잘못한거임?

**Comment by DaePokPung** [comment]
그게 그라이프발트 포커스 중 제국과의 협력 노선에서 Invite Imperial Industrialists 찍으면 그리포니아한테 발생하는 이벤트니까 주체가 그리포니아인게 맞음. 

국가 이벤트가 꼭 그 국가한테 발생하는 이벤트만 있는게 아니라 그 국가가 다른 국가에게 발생시키는 이벤트도 포함되어 있으니까 번역되는대로 이해하면 됨.

**Comment by DaePokPung** [comment]
그리고 이벤트 번역할때 선택지는 반말 설명 부분은 높임말로 해주면 감사하겠음 바닐라 한패가 그렇게 되어있어서

**Comment by UdongNick** [comment]
> 그리고 이벤트 번역할때 선택지는 반말 설명 부분은 높임말로 해주면 감사하겠음 바닐라 한패가 그렇게 되어있어서

그렇게 하고 있는데 그 에본윙 주교 정체 드러난 이후부터는 광신도들 특유의 교조적인 느낌 살리려고 존댓말 안 씀
