### ISSUE TITLE
번역 양식 관련해서 질문

### ISSUE THREAD

**Issue by keg0150** [DaePokPung/EquestriaAtWar-Korean-Translation#239]
"§Y2§! §R국제주의자§! 대의원이 의회로부터 소환되어 배치될 것입니다."

에서 Y2§! 는 2명이라는 뜻이잖아? 그럼 

"§Y2§!명의 §R국제주의자§! 대의원이 어쩌구--------." 하고 뒤에 <명의> 처럼 단위 붙여야함??

**Comment by DaePokPung** [comment]
단위 붙이는게 자연스러울듯 ㅇㅇ

**Comment by keg0150** [comment]
§!명의 처럼 다음에 느낌표 다음에 한글 붙여써도 되지?

**Comment by DaePokPung** [comment]
§! 이 아니라 !§ 아님? 암튼 붙여써도 됨
