### ISSUE TITLE
Communalist는 뭐라고 번역할까

### ISSUE THREAD

**Issue by keg0150** [DaePokPung/EquestriaAtWar-Korean-Translation#288]
일단 자치주의자라고 번역해 놨는데 공동체주의자가 나으려나? 평의회는 나라 체제랑 겹쳐서
아님 아예 코뮌주의자?

ps.너무 참여 안해서 미안하고 앞으로라도 열심히 참여하도록 하겠음

**Comment by DaePokPung** [comment]
ㄱㅊ그냥 하고싶은 생각나면 하면됨 나도 그리 열심히 하고있는건 아니라ㅋㅋ

그리고 Concessions to the Communalists 중점 설명 읽어봤는데 자치주의자로 놔두는게 흐름상 이해하기 편할거같음

**Comment by keg0150** [comment]
ㅇㅋㅇㅋ
