### ISSUE TITLE
어떻게 번역해야 할까

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#29]
"Republican Resistance"
The Republicans of Angriver have seen all they fought for ripped away after their moment of triumph, and are refusing to accept this lying down.

Memories of the Republic are fresh in their minds, and stamping it out will be no easy task.

일단 뒷 문장은 "공화국의 기억은 여전히 그들 마음 속에 남아 있으며 그것을 쓸어 내기는 쉽지 않을 것입니다."로 번역해 뒀는데 앞 문장을 번역하려고 보니까 막혀버렸음.

대충 "안그리버의 공화당은 패배했지만 공화국의 기억까지 쓸어내기는 어려울거다." 같은 내용이 되어야 맞을거 같은데 after their moment of triumph가 들어가 있어서 이렇게 번역할 수는 없고...

**Comment by tropico0410** [comment]
앞뒤문장 몰라서 문맥은 잘 모르겟지믄 '승리한 그들'이 공화당원의 반대편 세력인가보네

**Comment by DaePokPung** [comment]
영알못이라 문장구조 해석이 좀 어려운데... 일단 대강 때려맞춰보자면

설정상 안그리버의 아나키스트들이 978년 혁명 때 그리폰 공화국의 공화주의자들과 손을 잡고 혁명을 일으켰으나 실패했다는 점을 고려할때 moment of triumph는 그리폰 공화국이 이룩한 "잠깐의 승리"를 말하는 것 같고, all they fought for ripped away는 그렇게 공화주의자들이 열심히 건국한 공화국이 일년만에 망한걸 말하는거 같음. 즉 잠깐의 승리 이후 자신들이 싸워서 만든 모든 것들이 무너지는 것을 보았으며~ 같은 뉘앙스로 보면 될거같음
