### ISSUE TITLE
Unit=부대 맞지?

### ISSUE THREAD

**Issue by keg0150** [DaePokPung/EquestriaAtWar-Korean-Translation#308]
중대라고 할까 했는데 부대가 맞겠지?

p.s. 혹시 뭐 번역할지 고민인 사람들은 SRS 추천함 짱재밌는데 번역을 혼자해서 너무 느리다 진전이..

**Comment by DaePokPung** [comment]
부대가 나을듯
다음주에 시험끝나는대로 그리포니아 공화국 대충 마무리짓고 SRS들어가보겟음
