### ISSUE TITLE
번역 우선순위를 설정해야 하지 않을까

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#31]
그라이프발트, 안그리버같은 쩌리들도 800줄이나 되는데  이 인원이 이런 식으로 하면 결과다운 결과를 절대 못 낼거같음. 번역 속도보다 업뎃 속도가 훨씬 빠른거같기도 하고.

일단 이벤트, 포커스 텍스트 전부 건너뛰고 기술이나 정치같은 게임 내 필수 용어랑 이벤트, 포커스 효과부터 번역해야 할듯

**Comment by DaePokPung** [comment]
필요한것만 모아보자면

연구
[eaw_pony_techs_l_english.yml](localisation/eaw_pony_techs_l_english.yml)
[eaw_changeling_techs_l_english.yml](localisation/eaw_changeling_techs_l_english.yml)
[eaw_deer_techs_l_english.yml](localisation/eaw_deer_techs_l_english.yml)
[eaw_griffon_techs_l_english.yml](localisation/eaw_griffon_techs_l_english.yml)
[eaw_diamond_dog_techs_l_english.yml](localisation/eaw_diamond_dog_techs_l_english.yml)

효과 [eaw_flags_and_opinion_l_english.yml](localisation/eaw_flags_and_opinion_l_english.yml)
룰셋 [eaw_game_rules_l_english.yml](localisation/eaw_game_rules_l_english.yml)
국가정신 [eaw_ideas_l_english.yml](localisation/eaw_ideas_l_english.yml)
시작화면(설정) [eaw_welcomescreen_l_english.yml](localisation/eaw_welcomescreen_l_english.yml)

국가파일 건너뛰면 사실 할게 그리많은건 아님
그래도 배포할거면 적어도 굵직한 나라 몇개는 90퍼이상 번역하고 내놓아야할텐데 걱정이네
개인적으로는 제브리카 패치 나오기 전에 이퀘스트리아, 체인질링, 그리포니아제국, 리버공화국, 아퀼레이아, 윙바르디, 그리폰공화국, 1.7 리워크된 기타 쩌리들까지는 완성하고싶은데 될려나ㅋㅋ

**Comment by DaePokPung** [comment]
필요한것만 모아보자면

연구
[eaw_pony_techs_l_english.yml](../blob/master/localisation/eaw_pony_techs_l_english.yml)
[eaw_changeling_techs_l_english.yml](../blob/master/localisation/eaw_changeling_techs_l_english.yml)
[eaw_deer_techs_l_english.yml](../blob/master/localisation/eaw_deer_techs_l_english.yml)
[eaw_griffon_techs_l_english.yml](../blob/master/localisation/eaw_griffon_techs_l_english.yml)
[eaw_diamond_dog_techs_l_english.yml](../blob/master/localisation/eaw_diamond_dog_techs_l_english.yml)

효과 [eaw_flags_and_opinion_l_english.yml](../blob/master/localisation/eaw_flags_and_opinion_l_english.yml)
룰셋 [eaw_game_rules_l_english.yml](../blob/master/localisation/eaw_game_rules_l_english.yml)
국가정신 [eaw_ideas_l_english.yml](../blob/master/localisation/eaw_ideas_l_english.yml)
시작화면(설정) [eaw_welcomescreen_l_english.yml](../blob/master/localisation/eaw_welcomescreen_l_english.yml)
주 [state_names_l_english.yml](../blob/master/localisation/state_names_l_english.yml)

국가파일 건너뛰면 사실 할게 엄청나게 많은건 아님
그래도 배포할거면 적어도 굵직한 나라 몇개는 90퍼이상 번역하고 내놓아야할텐데 걱정이네
개인적으로는 제브리카 패치 나오기 전에 이퀘스트리아, 체인질링, 그리포니아제국, 리버공화국, 아퀼레이아, 윙바르디, 그리폰공화국까지는 완성하고싶은데 될려나ㅋㅋ

**Comment by UdongNick** [comment]
> 필요한것만 모아보자면
> 
> 연구
> [eaw_pony_techs_l_english.yml](../blob/master/localisation/eaw_pony_techs_l_english.yml)
> [eaw_changeling_techs_l_english.yml](../blob/master/localisation/eaw_changeling_techs_l_english.yml)
> [eaw_deer_techs_l_english.yml](../blob/master/localisation/eaw_deer_techs_l_english.yml)
> [eaw_griffon_techs_l_english.yml](../blob/master/localisation/eaw_griffon_techs_l_english.yml)
> [eaw_diamond_dog_techs_l_english.yml](../blob/master/localisation/eaw_diamond_dog_techs_l_english.yml)
> 
> 효과 [eaw_flags_and_opinion_l_english.yml](../blob/master/localisation/eaw_flags_and_opinion_l_english.yml)
> 룰셋 [eaw_game_rules_l_english.yml](../blob/master/localisation/eaw_game_rules_l_english.yml)
> 국가정신 [eaw_ideas_l_english.yml](../blob/master/localisation/eaw_ideas_l_english.yml)
> 시작화면(설정) [eaw_welcomescreen_l_english.yml](../blob/master/localisation/eaw_welcomescreen_l_english.yml)
> 주 [state_names_l_english.yml](../blob/master/localisation/state_names_l_english.yml)
> 
> 국가파일 건너뛰면 사실 할게 엄청나게 많은건 아님
> 그래도 배포할거면 적어도 굵직한 나라 몇개는 90퍼이상 번역하고 내놓아야할텐데 걱정이네
> 개인적으로는 제브리카 패치 나오기 전에 이퀘스트리아, 체인질링, 그리포니아제국, 리버공화국, 아퀼레이아, 윙바르디, 그리폰공화국까지는 완성하고싶은데 될려나ㅋㅋ

제브리카 패치 나올거 생각하면 많이 아득해지긴 하지... 

일단 어떤 물건인지 보여줘야 번역 유입이 생기든 말든 할 테니까 그전에 꼭 필요한 게임 용어들이랑 체인질링, 이퀘스트리아, 그리포니아, 아퀼레이아, 우리 마을 이렇게 5개는 확실히 끝내놔야 할거같음. 각 대륙 메이저 강대국 2개 씩이랑 우리 마을은 그냥 내가 글리머 좋아해서ㅎㅎ
