### ISSUE TITLE
쓰기 권한이 없는것 같습니다

### ISSUE THREAD

**Issue by AdHoc2675** [DaePokPung/EquestriaAtWar-Korean-Translation#330]
You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork AdHoc2675/EquestriaAtWar-Korean-Translation, so you can send a pull request. 라고 떠서 번역한 내용을 추가하고 싶어도 할 수 없네요. 원랜 안 이랬는데... 쓰기 권한을 얻을 수 있나요?

**Comment by DaePokPung** [comment]
밑에 Propose changes 버튼이 아예 안뜨는건가요?? 그게 떠도 pull request 하는데는 아무상관이 없는데

**Comment by AdHoc2675** [comment]
버튼이 떠 있긴 한데, 비활성화되었는지 살짝 흐릿하게 변해있고, 눌리지가 않습니다

**Comment by DaePokPung** [comment]
거기서 번역 파일을 수정하는건 되나요? 수정이 된다면 수정을 한 후에도 버튼이 활성화되지 않나요?
그래도 활성화되지 않으면 쓰기 권한만 주는 방법은 저도 모르겠는데 수정하신 부분 여기다가 올려주시면 일단 제가 대신 업데이트하겠습니다

**Comment by AdHoc2675** [comment]
https://docs.google.com/document/d/1rlXo4RspQ9P3V7ujVKS4Wm0Ip_wKSZIV98pte9fbZNw/edit?usp=sharing
구글 문서에 적어놨으니 공유하는데엔 문제가 없을 겁니다.

**Comment by AdHoc2675** [comment]
연필 모양의 버튼 (수정 버튼)을 누르고, 안의 내용을 수정하는건 가능한데 Propose changes 버튼이 비활성화 되어있어 제출이 불가능합니다.

**Comment by DaePokPung** [comment]
일단 올려주신건 수정했습니다
그리고 일단 임시로 collaborator 권한 초대장을 이메일로 보내드렸습니다 받으시면 아마 You’re making changes in a project 어쩌고 경고는 안뜰겁니다

**Comment by AdHoc2675** [comment]
경고는 안뜨는데 여전히 제출은 되지 않습니다.

오늘 확인해 봤는데 아무래도 크롬 브라우저가 구버전이라서 제출 버튼이 안 눌리는 것 같습니다. 최신 버전으로 업데이트되니 버튼이 눌리네요.
