### ISSUE TITLE
단어 번역에 관해

### ISSUE THREAD

**Issue by DaePokPung** [DaePokPung/EquestriaAtWar-Korean-Translation#38]
그리포니아 제국에서 대립하는 두 세력의 번역명에 대해

Archon : 아콘, 아르콘, 집정관
Duchess : 여공작, 공작부인

지금은 집정관/여공작으로 하고 있는데 혹시나 해서 의견 물어보고자함

그리고 나라이름중에 Yale Rectorate는 어케번역하면 좋을까
교육기관이 나라를 지배한다는 컨셉을 고려하면 예일 총장국? 예일 학장국? 쯤 되려나??

**Comment by UdongNick** [comment]
그라이프발트 번역할때 나온 Archon들은 일단 다들 집정관으로 번역했었음. 그리고 Yale Rectorate는 레드 플러드에 프랑스 예술국이라는 선례가 있으니까 예일 학술국 정도로 번역해도 괜찮지 않을까?

**Comment by DaePokPung** [comment]
오 괜찮은듯
