### ISSUE TITLE
우리 루나제국 호환 필요한듯

### ISSUE THREAD

**Issue by ghost** [DaePokPung/EquestriaAtWar-Korean-Translation#387]
파일이 싹 바껴서 원래 이벤트하고 추가된 이벤트하고 다 섞여버림

**Comment by DaePokPung** [comment]
호환작업하다가 몇번현타와서 잠시 놓고있었음
ㅎㅎ;;ㅋㅋ;;ㅈㅅ!!
빠른시일내로 업데이트하겟음
