### ISSUE TITLE
야크야키스탄/재키 애들 번역에 관해

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#47]
얘네 번역은 존댓말 말고 야크체로 해도 괜찮지 않을까?

**Comment by DaePokPung** [comment]
ㅇㅇ그것도 괜찮을듯

**Comment by UdongNick** [comment]
> ㅇㅇ그것도 괜찮을듯

그리고 야크야키스탄 스크립트에 [This.YakOrJakUppercase] 라는게 많이 나오던데 이게 뭘 뜻하는 거임?

**Comment by DaePokPung** [comment]
얘네들이 산업이나 군사  중점들을 공유해서 야크야키스탄에서는 야크, 재키부족에서는 재키로 출력되는 부분임
