### ISSUE TITLE
드레드리그 개인적으로 호감이야

### ISSUE THREAD

**Issue by tropico0410** [DaePokPung/EquestriaAtWar-Korean-Translation#64]
https://github.com/DaePokPung/EquestriaAtWar-Korean-Translation/blob/master/localisation/country_DED_l_english.yml

근데 중점 트리 일부러 반말로 번역한거임? 의도한 거면 나도 따르게

그리고 dread league 명칭은 그냥 드레드 리그라고 번역하는 게 깔끔할 거 같지?

**Comment by DaePokPung** [comment]
ㅇㅇ드레드리그로
이거 번역한사람은 다른문서(악투리우스기사단)도 반말로 번역해놨던데 딱히 의도가 있어선지는 모르겠음
다른문서 반말로 번역한거는 나중에 다른사람이 다시 높임말로 고쳤는데 별 말 없던걸로봐선 아마 이것도 원칙대로 높임말로 나중에 전부 고치는게 나을듯
