### ISSUE TITLE
체인질링 조언자 Great Imperial Nobody 말인데

### ISSUE THREAD

**Issue by Little-Mans** [DaePokPung/EquestriaAtWar-Korean-Translation#646]
'위대한 제국의 보잘것없는 자'보다는 '제국의 위대한 무명인'이 낫지 않을까요?

위대한 제국의 보다는 제국의 위대한이 문법에도 더 맞는거같고, 
무명인이 뜻은 같으면서 보잘것없는 자보다 훨씬 짧아서 더 나을거같은데

**Comment by DaePokPung** [comment]
저도 무명인이 더 괜찮아 보이네요
번역하신분 의견 기다려보고 별 말 없으시면 수정하겠습니다

**Comment by dorarararara** [comment]
근데 보잘것 없는 자와 무명인이 비슷함?

**Comment by Little-Mans** [comment]
> 근데 보잘것 없는 자와 무명인이 비슷함?

[국어사전]
무명인 (無名人)
1
이름 모를 사람.
2
세상에 널리 이름이 알려지지 않은 사람.

보잘것없다 [보잘꺼덥따] 듣기 
형용사 볼만한 가치가 없을 정도로 하찮다.

뜻 자체는 통해도 뉘앙스는 크게 다른거같기는 함. 그런데 '보잘것없는 자'는 너무 긴 것 같음. '아무도 모르는 사람'이라는 뜻인 다른 단어가 있을까?

**Comment by dorarararara** [comment]
그냥 하찮은 자라고 할까

**Comment by Little-Mans** [comment]
것도 괜찮은듯 '제국의 위대한 하찮은 자'로 번역하면 되나

**Comment by dorarararara** [comment]
그런듯

**Comment by Little-Mans** [comment]
그럼 다음 체인질링 번역하면 '제국의 위대한 하찮은 자'로 바꿔놓고 이 이슈는 마무리하면 되겠다
