### ISSUE TITLE
번역관련 자잘한 질문 몇가지

### ISSUE THREAD

**Issue by keg0150** [DaePokPung/EquestriaAtWar-Korean-Translation#76]
Offically the Order of Brothers of the Griffon House of Prelate Aloysious in Cloudbury the Knights of Hellquill have had a storied and bloody past.

얘는 어떻게 번역해야함? 대충 기사단은 피로 얼룩진 과거를 가졌다는 것 같은데 가운데에 of가 겁나많이 들어가서 포니알못인 나로서는 어디서 어떻게 번역해야할지 모르겠음

그리고 -an 부분은 어떻게 번역하는게 좋을 것 같음?

Hellquillians 얘를 헬퀼인으로 번역하기엔 '사람 인' 자가 너무 거슬려서 그냥 음차로 헬퀼리안이라고 번역해 놨는데 이대로 쭉 가도 되겠지?

**Comment by DaePokPung** [comment]
공식적으로 / cloudbury에 있는 / 알로이시우스 성직자의 / 그리폰 가문의 / 형제 기사단? / 은 은둔하고 피비린내 나는 과거를 가지고 있었다. 아마 이런방식인듯
an은 난 지금까지 마땅한게 없어서 -인으로 번역하긴 했는데... 그냥 본인 보기에 좋을거 같은대로 일단 적어봐 지금은 완성이 목표라서

**Comment by keg0150** [comment]
ㅇㅋㅇㅋ 알겠음

**Comment by UdongNick** [comment]
난 -an들 전부 시민, 국민으로 의역했음. 음역하긴 어색하고 -인으로 바꾸기도 사람 인자가 너무 거슬리고 해서...

**Comment by keg0150** [comment]
오 그거 좋은데? 그게 훨씬 나은듯
