### ISSUE TITLE
지금 만든거 테스트용으로 창작마당에 올릴까하는데

### ISSUE THREAD

**Issue by DaePokPung** [DaePokPung/EquestriaAtWar-Korean-Translation#79]
아직 배포할 수준은 한참 멀었긴 하다만
인겜에서 제대로 출력되어 나오는지(가끔 큰따옴표 빼먹어서 안나오는 경우가 있어서), 오타난거 한번 더 검수하고 글자 깨지는 부분 있는지, 이벤트 같은 경우 앞뒤 이벤트랑 단어랑 문맥이 맞게 흐르는지 이런거 나 혼자 보고 있는데

그냥 임시 모드 올려서 며칠 간격으로 업데이트하며 번역한 사람들이 자기꺼 시간나면 확인해보는 용도로 써먹을까 하는데 어떤거 같음?

배포는 아니라서 갤에다 홍보는 안할거임 물론 공개모드니까 누가 검색하다가 받아서 할 수도 있다만 어차피 번역된 부분은 거의 없으니까 받아봤자 사실 딱히 의미는 없음

**Comment by keg0150** [comment]
검수는 언젠가 해야하니까 지금 하는것도 좋지 않을까?

**Comment by UdongNick** [comment]
검수 생각하니까 그거도 또 토나오네

**Comment by UdongNick** [comment]
그래도 카라갤에서 포니모드 곧 허용될 분위기라 번역 인원이 좀 늘기는 할 듯
