### ISSUE TITLE
단어장의 몇몇 부분을 고치자

### ISSUE THREAD

**Issue by alkashir** [DaePokPung/EquestriaAtWar-Korean-Translation#83]
1. Equestria를 이퀘스트리아로 번역했는데, 에퀘스트리아로 바꿔야 한다. 아마 expensive/ɪkˈspɛnsɪv/나 exactly/ɪɡˈzæk(t)li/에서 볼 수 있듯이 영어 어두의 e가 [ɪ]로 소리나는 경우가 많아서 헛갈린 듯한데, Equestria는 영어로 /ɛˈkwɛstriə/로 발음하고 애니메이션에서도 이퀘스트리아가 아니라 에퀘스트리아로 발음함. 그러니 에퀘스트리아로 고치자.

2. principality를 공국으로 번역했는데 이는 duchy의 번역어와 겹친다. 영어 prince가 번역하기 어려운 말이지만 principality와 duchy는 분명히 다른 것이니 번역도 다르게 해야 한다. 개인적으로 principality는 후국, prince는 후작으로 번역하는 것이 어떨까 하는데. 물론 같은 prince라도 에퀘스트리아의 Prince Blueblood는 왕자로 번역하는 것도 고려해야겠지만.

3. Crystal Empire를 크리스탈 왕국으로 번역했는데, 아무리 작중의 Crystal Empire가 에퀘스트리아에 종속된 것이나 다름없다 해도, 아무리 Crystal Empire의 통치자가 empress가 아닌 princess인 것이 이상하다 해도, 원문에 empire로 적혔으니 번역도 제국으로 해야 맞다고 생각함. 개인적으로는 수정 제국으로 번역하길 바란다.

4. Dread League는 드레드 리그로 음역하지 말고 공포의 동맹으로 번역하면 어떨까?

5. Arcturian Order를 아크투리우스 기사단으로 번역했는데, 영어 Arcturian은 Arcturus+ian으로, 아크투리우스는 틀린 번역임. 영어 발음을 그대로 옮기면 아크튜어리언 오더가 되고 개인적으로 적절하다고 생각하는 번역어는 대각성 기사단이다. 굳이 음역한다면 아크튜어러스 기사단 또는 아르크투루스 기사단이 좋겠다. 그런데 order를 한국어로 무분별하게 기사단으로 번역하는 경향이 있는데 개인적으로 수도회로 번역하면 어떨까 생각함.

6. Angriver는 안그리버가 아닌 앵그리버가 맞다고 생각한다. 영어 rock의 표준 발음은 록/ɹɒk/이므로 Blackrock은 블랙락이 아닌 블랙록으로 번역하면 좋다고 생각한다. Marcher-Lordship of Westkeep은 번역어를 제시하지 않았는데 웨스트킵 변경백국이 어떨까? New Mareland는 뉴 메어랜드가 아니라 뉴메어랜드로 쓰는 것이 좋다고 생각한다. 뉴 욕이나 뉴 질랜드라고 표기하지 않는 것과 같은 이치임.

7. harmonist를 조화주의자로 번역하는 것은 어쩔 수 없지만, harmony를 굳이 조화주의라고 번역할 필요가 있을까? 이 모드에선 harmony가 정치 이념처럼 나오긴 하지만 '조화주의를 따르는 포니들' 같은 묘사보다는 '조화를 따르는, 조화의 이상을 따르는 포니들', 같은 묘사가 더 자연스럽다고 생각한다.

**Comment by DaePokPung** [comment]
1. 3. 발음상과는 무관하게, 공식적인 마이리틀포니 번역명은 "이퀘스트리아"와 "크리스탈 왕국"임. 이건 네이버나 구글에 검색해 봐도 알 수 있고, 투니버스(넷플릭스) 더빙도 이렇게 되어있음. 이렇게 공식 한국어 명칭으로 굳어진 이름을 바꿀 생각은 없음.

2. 나야 뭐 작위 이런건 잘 모르니... 크게 의미에 벗어나지 않으면 괜찮을듯

4. 글쎄... 난 세력 이름이면 몰라도 나라 이름에 형용사 표현이 들어가는거 개인적으로 별로임.

5. 아크투리우스는 다른 사람이 제안했던 거라서 그사람 오면 얘기해보셈 토론했던거 같은데 어디있는지 못찾겠네...

6. 앵그리버, 블랙록, 웨스트킵 변경백국 전부 괜찮다고 봄. 여기에 이의 추가로 없으면 이걸로 바꾸겠음

7. 단어장에도 적어놓았지만 "파시즘, 공산주의랑 구별되는 이념적 의미만으로 보기 애매할 경우 '조화'로 적어도 무방"하다고 적어놓았음. 이 말의 의도는 이념끼리 모아서 구분할 때 ~주의로 끝나는게 보기 편해서 그렇게 적은 거임. 조화든 조화주의든 혼용해도 아무 지장이 없기 때문에 조화로 쓰는게 낫다? 그럼 조화로 쓰면 됨.

**Comment by UdongNick** [comment]
대부분 좋은 지적이고 앞으로 이 지침에 맞게 번역하겠지만, 이퀘스트리아랑 크리스탈 왕국 같은 케이스는 나도 한국 정발명이 우선이라고 생각함

**Comment by UdongNick** [comment]
그리고 너무 발음 기호에 신경쓰면서 번역하면 정작 텍스트를 볼 때 어색해지지 않을까? 아크튜어러스같은 경우는 한국어에서는 하지 않는 장음 표기까지 하니까 그런 점이 더 가중되는거 같기도 하고. 나는 스2 아크튜러스의 선례를 따라서 아크튜러스로 표기하는게 적절하다고 생각함

order를 수도회로 번역할지 기사단으로 번역할지는 포커스 트리를 다 읽어보고 그 단체의 성격에 따라 결정해야 한다고 생각하는데, 아크튜러스의 경우 군사적인 성격, 명예를 중시하고 무를 숭상하는 사회 분위기 등을 감안해거 기사단으로 번역하는게 적절하다고 봄.

**Comment by DaePokPung** [comment]
일주일이 지났는데 다른 추가적인 의견 없으면 이대로 가겠음.

principality 후국
prince 후작
Arcturian Order 아크튜러스 기사단
Angriver 앵그리버
Blackrock 블랙록
Marcher-Lordship of Westkeep 웨스트킵 변경백국
New Mareland 뉴메어랜드
나머지 현행유지
