### ISSUE TITLE
번역 우선순위를 정하고 그거에 집중하자

### ISSUE THREAD

**Issue by UdongNick** [DaePokPung/EquestriaAtWar-Korean-Translation#86]
사실 전에도 한 번 했던 얘기인데 보니까 테스트용으로 창작마당에 올리자는 얘기까지 나오길래 다시 올려봄.

인원을 모으려면 내용물을 까서 홍보를 하거나 연재를 해야 하는데 지금 너무 중구난방으로 작업이 진행 중인거같음. 체인질링은 시작도 못한 데다가 이퀘스트리아는 반 살짝 넘긴 상태인데 내전 국가들은 마찬가지로 손도 안 댄 상태임.

그나마 한패 대장이 이 모드 내용물에 대해서는 제일 잘 알테니까 알아서 우선 번역 파일 목록을 만들어서 올리고, 그것들을 후딱 끝내는게 좋을거같음.

**Comment by DaePokPung** [comment]
번역 파일 목록이라는게 어떤거임? 지난번 토론에서 말했던 번역 우선순위 국가들?
사실 그것들도 언제 될지 모르겠어서 이퀘스트리아, 그리포니아 두 개부터 먼저 다 끝내고 싶긴한데. 이퀘는 하는사람들 몇 있었고 그리포니아는 내가 조금씩 하고 있으니까.
그럼 일단 메이저 4개국 링크를 메인화면에 걸어놓으면 되는건가?

**Comment by UdongNick** [comment]
> 번역 파일 목록이라는게 어떤거임? 지난번 토론에서 말했던 번역 우선순위 국가들?
> 사실 그것들도 언제 될지 모르겠어서 이퀘스트리아, 그리포니아 두 개부터 먼저 다 끝내고 싶긴한데. 이퀘는 하는사람들 몇 있었고 그리포니아는 내가 조금씩 하고 있으니까.
> 그럼 일단 메이저 4개국 링크를 메인화면에 걸어놓으면 되는건가?

이퀘스트리아(내전 국가들까지), 체인질링, 그리포니아 이렇게 3개에다가 내가 그리포니아 제국 정세를 잘 몰라서 그러는데 그리포니아의 최대 라이벌 하나까지 끼워서 4개부터 끝내자.

**Comment by DaePokPung** [comment]
내전국이 한둘이 아닌데 일단은 라스페가수스, 밴후버 같은 쩌리들은 제외하고 나이트메어 문이랑 데이브레이커까지만 포함하자
그러면
- 이퀘스트리아
- 루나 제국
- 태양 제국
- 체인질링 랜드
- 그리포니아 제국
- 그리폰 공화국
하면 되겠네

**Comment by UdongNick** [comment]
이퀘스트리아는 내가 좀 하고 있었음

> 내전국이 한둘이 아닌데 일단은 라스페가수스, 밴후버 같은 쩌리들은 제외하고 나이트메어 문이랑 데이브레이커까지만 포함하자
> 그러면
> 
> * 이퀘스트리아
> * 루나 제국
> * 태양 제국
> * 체인질링 랜드
> * 그리포니아 제국
> * 그리폰 공화국
>   하면 되겠네

혹은 아예 그리포니아를 건너뛰고 이퀘스트리아(내전으로 생성되는 쩌리 국가들까지 전부), 체인질링 랜드에 집중하는게 좋을 수도 있고

**Comment by DaePokPung** [comment]
포니에 거부감 느끼는 사람들 많아서 접근성 높이려면 그리폰 국가 적어도 하나는 필요하다고 생각함
개인적으로 그리포니아 대륙 역사 자체를 관통하는 스토리를 가진 그리포니아 제국만큼은 번역이 필요하다는게 내 생각... 최대한 빨리 끝내고 이퀘 쪽으로 들어가겠음

**Comment by UdongNick** [comment]
> 포니에 거부감 느끼는 사람들 많아서 접근성 높이려면 그리폰 국가 적어도 하나는 필요하다고 생각함
> 개인적으로 그리포니아 대륙 역사 자체를 관통하는 스토리를 가진 그리포니아 제국만큼은 번역이 필요하다는게 내 생각... 최대한 빨리 끝내고 이퀘 쪽으로 들어가겠음

ㅇㅋ

**Comment by UdongNick** [comment]
포니가 싫으면 헬퀼 기사단이 딱이야

**Comment by keg0150** [comment]
무분별한 포니 혐오를 멈춰주세요

**Comment by UdongNick** [comment]
> 내전국이 한둘이 아닌데 일단은 라스페가수스, 밴후버 같은 쩌리들은 제외하고 나이트메어 문이랑 데이브레이커까지만 포함하자
> 그러면
> 
> * 이퀘스트리아
> * 루나 제국
> * 태양 제국
> * 체인질링 랜드
> * 그리포니아 제국
> * 그리폰 공화국
>   하면 되겠네

그리고 이 목록들은 깃헙 대문 맨 위에 박거나, 번역 모집글 구할때 넣거나 해서 많이들 보고 따르게 해주셈

**Comment by DaePokPung** [comment]
> 무분별한 포니 혐오를 멈춰주세요

응 포확찢할거야~~

> 그리고 이 목록들은 깃헙 대문 맨 위에 박거나, 번역 모집글 구할때 넣거나 해서 많이들 보고 따르게 해주셈

ㅇㅋㅇㅋ

**Comment by alkashir** [comment]
임페리움 크리스탈리스는 메이저 나라는 아닌가? 내가 번역하려 했는데.

**Comment by DaePokPung** [comment]
크리스탈 왕국 솜브라 내전 생성국인가 거기가? 메이저라면 메이저긴 한데... 분량이 적어서 빠르게 끝낼 수 있을거 같으면 번역하고 아니면 위에 저것들부터 해주면 감사하겠음

**Comment by UdongNick** [comment]
> 크리스탈 왕국 솜브라 내전 생성국인가 거기가? 메이저라면 메이저긴 한데... 분량이 적어서 빠르게 끝낼 수 있을거 같으면 번역하고 아니면 위에 저것들부터 해주면 감사하겠음

CRY_SOL, CRY_NLR 둘은 뭐임? 이퀘스트리아 내전에 따라서 크리스탈 왕국도 바뀌는 부분이 있나

**Comment by DaePokPung** [comment]
ㅇㅇ 아마 각자의 괴뢰국이 되었을 때 바뀌는 걸거임
